### ISSUE TITLE
Formatting issue (title sometimes has bigger font than other title)

### ISSUE THREAD

**Issue by sundaradinakar** [arnabsinha83/TestAcademicAPI#5]
![image](https://cloud.githubusercontent.com/assets/15331151/17150082/e1f1bf14-5322-11e6-9f8a-036074f97baa.png)

In the pic, C has bigger font than A B & D

**Comment by arnabsinha83** [comment]
The all uppercase title is actually the fault of the dataset. I know this because we aggregate papers from the Web where the titles are sometimes noisy. We try to clean it up as much as possible. But sometimes it still persists. And we don't want to fix the casing ourselves because it can mess with titles like "SoRec: social recommendation using probabilistic matrix factorization"
